# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 00:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('middle_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('gender', models.CharField(max_length=2)),
                ('joining_year', models.CharField(max_length=10)),
                ('blood_grp', models.CharField(default=None, max_length=20)),
                ('role', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GuestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_gender', models.CharField(max_length=2)),
                ('no_of_stay', models.IntegerField(default=None)),
                ('guest_name', models.CharField(default=None, max_length=100)),
                ('guest_age', models.IntegerField(default=None)),
                ('relation', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HostelComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(default=None, max_length=500)),
                ('complain_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='InOutList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.CharField(default=None, max_length=200)),
                ('out_time', models.CharField(default=None, max_length=200)),
                ('out_reason', models.CharField(default=None, max_length=500)),
                ('out_place', models.CharField(default=None, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MobileNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoomRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_room_no', models.IntegerField(default=0)),
                ('fee_proof', models.FileField(default=None, upload_to=b'')),
                ('hostel_name', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default=None, max_length=50, null=True)),
                ('rollno', models.CharField(default=None, max_length=50, unique=True)),
                ('middle_name', models.CharField(default=None, max_length=50, null=True)),
                ('last_name', models.CharField(default=None, max_length=50, null=True)),
                ('regis_year', models.IntegerField(default=None, null=True)),
                ('gender', models.CharField(max_length=2, null=True)),
                ('curr_year', models.IntegerField(default=None, null=True)),
                ('regis_deg', models.CharField(default=None, max_length=20, null=True)),
                ('regis_deg_dur', models.IntegerField(default=None, null=True)),
                ('curr_sem', models.IntegerField(default=None, null=True)),
                ('blood_grp', models.CharField(default=None, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='roomregistration',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student'),
        ),
        migrations.AddField(
            model_name='mobileno',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inoutlist',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student'),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student'),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student'),
        ),
    ]
